<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>自定义Promise_使用测试</title>
</head>

<body>
  <script src="./lib/Promise4.js"></script>
  <!-- 
    1. promise的链式调用
    2. 执行顺序问题
   -->
  <!-- <script>
    const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(1)
        // reject(2)
        // throw 3
      }, 100);
      
    })

    p.then(
      value => {
        console.log('onResolved()', value)
        // return 4
        throw 5
        // return new Promise((resolve, reject) => resolve(4))
        // return new Promise((resolve, reject) => reject(5))
      },
      reason => {
        console.log('onRejected()', reason)
        // return 6
        // throw 7
      }
    ).then(
      value => {
        console.log('onResolved2()', value)
      },
      reason => {
        console.log('onRejected2()', reason)
        throw 8
      }
    ).catch(reason => {
      console.log('onRejected3()', reason)
    }).then(
      value => {
        console.log('onResolved4()', value)
      },
      reason => {
        console.log('onRejected4()', reason)
      }
    )

    /* 
    then()返回的是一个新的promise对象, 它的结果由这个then()指定的回调函数的结果来决定
    
    */
  </script> -->

  <script>
    const p1 = Promise.resolve(1)
    const p2 = Promise.resolve(Promise.resolve('atguigu'))
    const p3 = Promise.reject(true)

    // const p4 = Promise.all([ p2, p1, p3])
    // const p4 = Promise.all([p2, p1, 3])
    // const p4 = Promise.race([ p3, p2, p1])
    const p4 = Promise.race([ p2, p1, p3])
    p4.then(
      values => console.log('完全成功了', values),
      reason => console.log('失败了', reason)
    )
  </script>


</body>

</html>